### ISSUE TITLE
Concerns::Susanoo::PageAssetsController#respond_with_asset で意図しない JavaScript が実行されるおそれがある

### ISSUE THREAD

**Issue by shao1555** [NaCl-Ltd/pref-shimane-cms#1]
ref: https://github.com/NaCl-Ltd/pref-shimane-cms/blob/master/pref-shimane-cms/app/controllers/concerns/susanoo/page_assets_controller.rb#L65
https://github.com/NaCl-Ltd/pref-shimane-cms/blob/master/pref-shimane-cms/app/controllers/concerns/susanoo/page_assets_controller.rb#L70

`params[:CKEditorFuncNum]` を直接代入している箇所があり、攻撃者が任意の JavaScript コードを実行することができてしまいます。

**Comment by gokitagawa** [comment]
ご報告ありがとうございます。
修正が完了しましたらまたコメントさせていただきます。

**Comment by nacl-anno** [comment]
大変遅くなりましたが、修正完了しました。
ご報告誠にありがとうございます。
